#!/bin/bash
# Coded by BajeTech (AliByte01)
# Note: THIS IS NOTHING OUT OF BASH SCRIPT TO INSTALL THE REQUIREMENTS OF THE TOOL

clear
pkg install python -y
pip install lolcat
clear
sleep 0.0
echo " ____  _____ _____ _   _ ____"|lolcat 
echo "/ ___|| ____|_   _| | | |  _ \ "|lolcat
echo "\___ \|  _|   | | | | | | |_) |"|lolcat
echo " ___) | |___  | | | |_| |  __/ "|lolcat
echo "|____/|_____| |_|  \___/|_| "|lolcat
echo ""
sleep 1.0
echo "BY RUNING THIS YOU MEAN YOU WANNA SETUP THE TermuxTheme"|lolcat
echo ""
read -p "TO CONTINUE SETUP PRESS ENTER TO CANCEL PRESS CTRL + Z"
echo ""
echo "THE SETTING UP HAS GET STARTED NOW THIS MAY TAKE A WHILE"|lolcat
sleep 1.0
pkg update -y && pkg upgrade -y
pkg install python3 -y
pkg install git -y
pip3 install lolcat
pkg install mpv -y
pkg install figlet -y
pkg install toilet -y
pkg install ruby -y
pip install lolcat
gem install lolcat
clear
echo "MashAllah all setup you are ready good to go now."|lolcat
echo "Please Run ./TermuxTheme.sh To Start The Tool."|lolcat
sleep 3.0
echo "am listing the file to run for you to see."
sleep 2.0
ls
